name: Tree-sitter parse files
description: Parse a corpus of files with tree-sitter

branding:
  color: green
  icon: align-left

inputs:
  files:
    description: Glob patterns of files to be parsed
    required: true
  invalid-files:
    description: Glob patterns of files that are invalid
  invalid-files-list:
    description: File with glob patterns of files that are invalid
  tree-sitter:
    description: The tree-sitter executable
    default: node_modules/.bin/tree-sitter

outputs:
  failures:
    description: The files with parsing errors

runs:
  using: node20
  main: dist/index.js
