name: Tree-sitter parse files
description: Parse a corpus of files with tree-sitter

branding:
  color: green
  icon: align-left

inputs:
  files:
    description: The glob patterns of the files to parse
    required: true
  tree-sitter:
    description: The tree-sitter executable
    default: node_modules/.bin/tree-sitter

outputs:
  failures:
    description: The files with parsing failures

runs:
  using: node20
  main: dist/index.js
